name: Keybase-AutoBackup-RadicalCommunity

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  auto-commit-action:
    if: steps.auto-commit-action.outputs.changes_detected == 'true'
    runs-on: ubuntu-latest
    
    steps:
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.9.1
      with:
        commit_message: Backup file changes - auto
